name: 'Build geoBingAn Frontend'
on:
  workflow_call:
    inputs:
      ENV_FILE_PATH:
        required: false
        type: string
      SKIP_FRONTEND:
        required: false
        type: string
jobs:
  init_job:
    uses: ./.github/workflows/r_init_job.yml
    with:
      ENV_FILE_PATH: .github/workflows/deploy.env
    secrets: inherit
  build_frontend:
    name: 'Debug ENV variables'
    needs: ["init_job"]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        lang: ['zh', 'en']
    steps:
      - name: 'Generate GitHub Actions Job Level Env'
        id: init
        run: |
          echo "Build geoBingAn Frontend with init job"
          echo "check needs.init_job.outputs.SKIP_FRONTEND variable"
          echo ${{ needs.init_job.outputs.SKIP_FRONTEND }}
          exit 1