name: 'Build geoBingAn Frontend without init job'
on:
  workflow_call:
    inputs:
      ENV_FILE_PATH:
        required: false
        type: string
      SKIP_FRONTEND:
        required: false
        type: string
jobs:
  build_frontend:
    name: 'Debug ENV variables'
    needs: ["init_job"]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        lang: ['zh', 'en']
    steps:
      - name: 'Generate GitHub Actions Job Level Env'
        id: init
        run: |
          echo "Build geoBingAn Frontend without init job"
          echo ${{ needs.init_job.outputs.SKIP_FRONTEND }}
          exit 1